"""empty message

Revision ID: 246c70652311
Revises: b8fc9cf4a9b1
Create Date: 2019-03-11 14:48:26.555266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246c70652311'
down_revision = 'b8fc9cf4a9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], name=op.f('fk_chat_family_id_family')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat'))
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=400), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('fk_chat_message_chat_id_chat')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_message_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('chat')
    # ### end Alembic commands ###
