"""empty message

Revision ID: 52228d4115dc
Revises: 43e76c2e4b85
Create Date: 2018-11-26 08:30:26.902291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52228d4115dc'
down_revision = '43e76c2e4b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
