"""empty message

Revision ID: 8e81fb2c2919
Revises: 9abfc57d56cd
Create Date: 2019-03-16 17:35:30.238553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e81fb2c2919'
down_revision = '9abfc57d56cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud', schema=None) as batch_op:
        batch_op.alter_column('dir_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud', schema=None) as batch_op:
        batch_op.alter_column('dir_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
